/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline-variant": "#584235",
        "surface-container-lowest": "#050505",
        "primary": "#ff7a00",
        "on-secondary": "#442b00",
        "on-tertiary": "#313030",
        "surface": "#0a0a0a",
        "secondary-container": "#ffae00",
        "on-tertiary-fixed-variant": "#474746",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed": "#ffddb1",
        "tertiary-fixed-dim": "#c8c6c5",
        "tertiary-fixed": "#e5e2e1",
        "on-surface-variant": "#e0c0af",
        "on-error": "#690005",
        "on-primary": "#000000",
        "inverse-primary": "#994700",
        "on-secondary-fixed-variant": "#614000",
        "surface-bright": "#1a1a1a",
        "background": "#050505",
        "on-secondary-fixed": "#291800",
        "error": "#ffb4ab",
        "primary-fixed": "#ffdbc8",
        "on-background": "#e5e2e1",
        "surface-tint": "#ff7a00",
        "surface-variant": "#1f1f1f",
        "surface-container-low": "#111111",
        "on-surface": "#e5e2e1",
        "outline": "#a78b7c",
        "error-container": "#93000a",
        "secondary": "#ffd395",
        "surface-container-highest": "#2a2a2a",
        "on-tertiary-fixed": "#1c1b1b",
        "surface-dim": "#050505",
        "primary-fixed-dim": "#ffb68b",
        "primary-container": "#ff7a00",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#161616",
        "surface-container": "#0e0e0e",
        "inverse-on-surface": "#313030",
        "on-tertiary-container": "#373737",
        "on-primary-fixed": "#321200",
        "secondary-fixed-dim": "#ffba48",
        "tertiary": "#c8c6c5",
        "on-secondary-container": "#6a4600",
        "on-primary-container": "#000000",
        "tertiary-container": "#a2a0a0",
        "on-primary-fixed-variant": "#753400"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "48px",
        "gutter": "24px",
        "margin": "32px",
        "xs": "4px",
        "sm": "12px",
        "base": "8px",
        "xl": "80px",
        "md": "24px"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "display-xl": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display-xl": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
